# -*- coding: utf-8 -*-
"""XGBoost_GPU (3) (4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2wwP-XsnNWlVj52sLsFpK0IZ7PwWkV-

Here is a summary of how this pipeline translates P2Rank's methodology into a highly parallelized, GPU-native architecture for pocket druggability prediction:

**Core Pipeline and GPU Integration**
Spatial Hashing & Grid Construction: The script calculates a 3D bounding box divided into a 4.0 Ångstrom resolution grid. It uses custom C++ CUDA kernels (calc_hash and find_cell_bounds) compiled via CuPy to rapidly assign every protein atom to a specific grid cell. All physical arrays, including coordinates, charges, and element IDs, are reordered to match this spatial grid to ensure optimal memory access during feature extraction.

**Solvent-Accessible Surface (SAS) Simulation:** The pipeline mocks a solvent-accessible surface by generating 500,000 random spatial sample points around the protein. A custom CUDA kernel evaluates these points, dynamically rejecting any that sterically clash with the protein interior by falling within a 2.5 Ångstrom cutoff.

**Native Geometric Featurization:** Instead of relying on CPU-bound RDKit SMARTS matching, a custom CUDA kernel (aggregate_features) extracts biophysical features geometrically. For each valid SAS point, the GPU computes localized electrostatic potential, neighbor atom counts, and the spatial densities of pharmacophores (such as H-bond donors, acceptors, hydrophobes, and aromatics) directly in VRAM.

**High-Performance Clustering:** After predicting ligandability scores, the pipeline dynamically filters out the top 10% highest-scoring surface points. It then deploys the DBSCAN algorithm from the cuML library to perform spatial clustering entirely on the GPU. This groups points within 4.0 Ångstroms of each other into discrete pockets, requiring a minimum of 10 points to form a valid cluster.

**Ranking:** Once clustered, the algorithm calculates the 3D geometric center (centroid) of each pocket. Pockets are scored by summing the individual probabilities of all the points contained within that cluster, and are subsequently ranked in descending order based on this total score.

**Machine Learning Models Utilized**
**XGBoost Regressor (Active Model):** The script explicitly replaces P2Rank's traditional CPU-based Random Forest classifier with a GPU-accelerated XGBoost regression model. By utilizing the parameters tree_method='hist' and device='cuda', the model builds sequential decision trees and calculates gradient math natively on the GPU's CUDA cores. This ensures a zero-copy data execution environment, meaning the massive CuPy feature arrays never leave the GPU's VRAM during training or inference.

Random Forest (Baseline/Inspiration): The documentation notes that standard P2Rank relies on a Random Forest classifier. This approach was abandoned in this script because Random Forests are typically CPU-bound, whereas XGBoost's histogram binning is heavily optimized for execution on GPUs.

E(3) Equivariant Graph Neural Networks (Future Architecture): The notebook concludes by outlining that E(3) Equivariant Neural Networks represent the next logical evolution of this pipeline. While XGBoost relies on hand-engineered, distance-based scalar features, an E(3) EGNN would natively ingest raw 3D atomic coordinates as a spatial graph. This allows the model to utilize tensor mathematics to learn directional vectors and universal biophysics without relying on human-engineered feature extraction.

# What is GPU-Accelerated XGBoost?

* XGBoost is an open-source software library that implements optimized distributed gradient boosting machine learning algorithms, providing parallel tree boosting for regression, classification, and ranking problems.

* The library has gained significant favor in recent years due to its highly accurate implementation of gradient boosting and its ability to push the limits of computing power, especially when accelerated with NVIDIA GPUs.

* XGBoost has been integrated with various tools and packages, including scikit-learn and Apache Spark, and its GPU-accelerated version enables faster model training and improved accuracy, making it a premier choice for machine learning tasks.

* GPU-accelerated XGBoost has been successfully applied to various use cases, such as predicting taxi fares and housing prices, demonstrating its potential to accelerate time to insights and improve model performance.

* NVIDIA's RAPIDS platform and GPU-accelerated workstations further enhance the performance of XGBoost, providing end-to-end data science pipelines and enabling data scientists to build highly accurate models faster.

https://www.nvidia.com/en-gb/glossary/xgboost/
"""

!pip install rdkit py3Dmol pdb2pqr

"""# 🧬 End-to-End GPU-Accelerated Pocket Prediction Pipeline

This notebook implements a highly optimized machine learning pipeline designed to predict and visualize ligand-binding pockets on a protein's surface. Its core strength lies in its heavy reliance on **GPU acceleration** (using libraries like CuPy, cuML, and custom CUDA kernels) to perform mathematically intensive spatial calculations and model training natively on the GPU, avoiding costly CPU-GPU data transfers.

---

## 🛠️ Pipeline Breakdown

### 1. Data Loading and Setup

### 2. Spatial Hashing and Grid Construction

### 3. Surface Simulation and Feature Extraction

### 4. XGBoost regression model Training

### 5. XGBoost regression model Inference

### 6. DBSCAN Pocket Clustering and Segmentation

---
"""

#@title Downloads the 3D structure for a specific protein (PDB ID `5RMM`) using the RDKit library. Target Isolation: Filters the protein structure to isolate only the atoms belonging to **Chain B**.
import urllib.request
import time
import numpy as np
import cupy as cp
from rdkit import Chem

# ==========================================
# 0. Setup Environment & Fetch Real PDB
# ==========================================
pdb_id = "5RMM"
pdb_filename = f"{pdb_id}.pdb"
print(f"1. Downloading and parsing {pdb_id} via RDKit...")
start_step_0 = time.time()

urllib.request.urlretrieve(f"https://files.rcsb.org/download/{pdb_id}.pdb", pdb_filename)

# Clean the PDB file: Remove Chain A and Water (HOH) residues
print("  -> Cleaning PDB: Removing Chain A and Water (HOH)...")
with open(pdb_filename, "r") as f:
    lines = f.readlines()

with open(pdb_filename, "w") as f:
    for line in lines:
        if line.startswith(("ATOM", "HETATM")):
            res_name = line[17:20].strip()
            chain_id = line[21]
            if chain_id == 'A' or res_name == 'HOH':
                continue
        f.write(line)

protein_mol = Chem.MolFromPDBFile(pdb_filename, sanitize=False)


# Filter for Chain B
chain_b_indices = [
    atom.GetIdx() for atom in protein_mol.GetAtoms()
    if atom.GetPDBResidueInfo() is not None and atom.GetPDBResidueInfo().GetChainId() == 'B'
]
#Extract the N x 3 coordinate matrix from the conformer
num_atoms = len(chain_b_indices)
positions = protein_mol.GetConformer().GetPositions()[chain_b_indices] # Returns a standard NumPy array

print(f"Filtered structure to {num_atoms} atoms from Chain B.")

end_step_0 = time.time()
elapsed_ms = (end_step_0 - start_step_0) * 1000
print(f"Execution time: {elapsed_ms:.2f} ms")

"""# Biophysical Preparation:"""

#@title # Run PDB2PQR to add hydrogens at pH 7.4 using the AMBER forcefield and PROPKA
import time

# Run PDB2PQR to add hydrogens at pH 7.4 using the AMBER forcefield and PROPKA
start_pqr = time.time()
!pdb2pqr --ff=AMBER --titration-state-method=propka --with-ph=7.4 --pdb-output 5RMM_prepared.pdb 5RMM.pdb 5RMM_prepared.pqr
end_pqr = time.time()

print("Protein protonation at pH 7.4 complete. Saved as 5RMM_prepared.pdb")
print(f"PDB2PQR process took {end_pqr - start_pqr:.2f} seconds.")

#@title Load 5RMM_prepared.pdb into RDKit with sanitize=True and run Chem.AddHs() to ensure the molecule is chemically valid.
from rdkit import Chem

# Load 5RMM_prepared.pdb into RDKit without sanitization
pdb_file = "5RMM_prepared.pdb"
mol = Chem.MolFromPDBFile(pdb_file, sanitize=False)

if mol:
    print(f"Successfully loaded '{pdb_file}' with sanitize=False.")
    # Check if hydrogens are added by counting atoms with atomic number 1 (Hydrogen)
    num_hydrogens = sum(1 for atom in mol.GetAtoms() if atom.GetAtomicNum() == 1)
    if num_hydrogens > 0:
        print(f"Check successful: {num_hydrogens} explicit hydrogens are present in the structure.")
    else:
        print("Check failed: No explicit hydrogens found in the structure.")
else:
    print(f"Failed to load '{pdb_file}'.")

#@title Visualise .pqr file confirm hydrogens and electrostatic potential surface map
import py3Dmol

# Initialize the 3D viewer
view = py3Dmol.view(width=800, height=600)

# Set the background to black for better contrast
view.setBackgroundColor('black')

# Load the prepared PQR file to give py3Dmol access to the AMBER charges
with open("5RMM_prepared.pqr", "r") as f:
    view.addModel(f.read(), "pqr")

# Set default style to a combination of cartoon and thin sticks to see the protein model clearly
view.setStyle({'model': -1}, {'cartoon': {'color': 'lightgray'}, 'stick': {'radius': 0.15}})

# Explicitly set hydrogen atoms to white sticks
view.addStyle({'elem': 'H'}, {'stick': {'color': 'white', 'radius': 0.1}})

# Make Residue 405 stand out to ensure we are looking at the right spot
view.addStyle({'resi': 405}, {'stick': {'colorscheme': 'greenCarbon', 'radius': 0.25}})

# 3. Add the True AMBER Electrostatic Surface
# ==========================================
view.addSurface(py3Dmol.VDW, {
    'opacity': 0.70,         # LOWERED opacity so labels can show through the surface
    'colorscheme': {
        'prop': 'partialCharge', # 'partialCharge' is where 3Dmol.js stores PQR charges
        'gradient': 'rwb',       # Valid Red-White-Blue gradient
        'min': -0.5,             # Clamp minimum charge boundary
        'max': 0.5               # Clamp maximum charge boundary
    }
}, {'model': 0})

# 4. Troubleshoot: Render Labels for a Subset of Atoms
# ==========================================
# Rendering 9,000+ labels crashes the WebGL viewer.
# We restrict the labels to a single residue (e.g., Residue 405) so they render successfully.
view.addPropertyLabels('partialCharge', {'resi': 405}, {
    'fontSize': 14,
    'fontColor': 'black',
    'backgroundColor': 'white',
    'backgroundOpacity': 0.9,
    'showBackground': True
})

# Center the view and display
view.zoomTo({'resi': 405})
view.show()

#@title Step 1: Python PQR Parser -> GPU VRAM (RDKit-Free)
# ==========================================================================
# This cell completely replaces RDKit's Chem.MolFromPDBFile for the protein
# target. Instead of expensive topological chemistry perception, it reads the
# .pqr file as raw text and emits 1D flat numerical arrays that are pushed
# straight into GPU VRAM. All pharmacophore perception is done geometrically:
#   * X, Y, Z coordinates and AMBER partial charges are read from the columns.
#   * Element IDs (atomic numbers) are derived from the atom name.
#   * Aromatic ring atoms (PHE/TYR/TRP/HIS sidechains) are pre-tagged.
#   * Hydrogen-bond donors are pre-tagged with a native SciPy distance search.
# ==========================================================================
import numpy as np
import cupy as cp
from scipy.spatial import cKDTree
import time

pqr_file = "5RMM_prepared.pqr"

print("Step 1: Parsing PQR as raw text (RDKit abandoned for the protein target)...")
start_parse = time.time()

# Sidechain aromatic-ring atom names per residue (used for the is_aromatic tag).
AROMATIC_RING = {
    "PHE": {"CG", "CD1", "CD2", "CE1", "CE2", "CZ"},
    "TYR": {"CG", "CD1", "CD2", "CE1", "CE2", "CZ"},
    "TRP": {"CG", "CD1", "CD2", "NE1", "CE2", "CE3", "CZ2", "CZ3", "CH2"},
    "HIS": {"CG", "ND1", "CD2", "CE1", "NE2"},
    # PDB2PQR emits protonation-state variants of Histidine:
    "HID": {"CG", "ND1", "CD2", "CE1", "NE2"},
    "HIE": {"CG", "ND1", "CD2", "CE1", "NE2"},
    "HIP": {"CG", "ND1", "CD2", "CE1", "NE2"},
}

# Map an element symbol to its atomic number (Element ID).
ELEMENT_Z = {"H": 1, "C": 6, "N": 7, "O": 8, "P": 15, "S": 16}

# Residue sets used to tag ionizable centers and zinc-binding groups.
ZINC_BINDER_RES = {'CYS', 'HIS', 'ASP', 'GLU'}
POS_IONIZABLE_RES = {'ARG', 'LYS', 'HIP'}
NEG_IONIZABLE_RES = {'ASP', 'GLU'}

xs, ys, zs, charges, elements, aromatics, atom_names = [], [], [], [], [], [], []
pos_ions, neg_ions, zn_binders = [], [], []

with open(pqr_file, "r") as f:
    for line in f:
        if not line.startswith(("ATOM", "HETATM")):
            continue
        parts = line.split()
        try:
            # PQR row layout (chain ID is optional, so we index from the right):
            #   ... X Y Z CHARGE RADIUS
            float(parts[-1])                 # radius (last column) - parsed for validation
            charge = float(parts[-2])        # AMBER charge (second-to-last column)
            x = float(parts[-5])
            y = float(parts[-4])
            z = float(parts[-3])
        except (ValueError, IndexError):
            continue

        atom_name = parts[2]
        res_name = parts[3]

        # Derive the chemical element from the atom name (strip any leading digits).
        symbol = atom_name.lstrip("0123456789")[:1].upper()
        z_num = ELEMENT_Z.get(symbol, 0)

        # Pre-tag geometric categories
        is_arom = 1.0 if atom_name in AROMATIC_RING.get(res_name, ()) else 0.0

        # NEW: PosIonizable based on structural nomenclature (Nitrogens in basic groups)
        is_pos = 1.0 if (res_name in POS_IONIZABLE_RES and atom_name in {'NZ', 'NH1', 'NH2', 'ND1', 'NE2'}) else 0.0

        # NEW: NegIonizable based on structural nomenclature (Carboxylate and C-Terminal Oxygens)
        is_neg = 1.0 if ((res_name in NEG_IONIZABLE_RES and atom_name in {'OD1', 'OD2', 'OE1', 'OE2'}) or atom_name == 'OXT') else 0.0

        # ZnBinder remains unchanged
        is_zn = 1.0 if (res_name in ZINC_BINDER_RES and (atom_name == 'SG' or z_num in (7, 8))) else 0.0

        xs.append(x); ys.append(y); zs.append(z)
        charges.append(charge)
        elements.append(z_num)
        aromatics.append(is_arom)
        pos_ions.append(is_pos)
        neg_ions.append(is_neg)
        zn_binders.append(is_zn)
        atom_names.append(atom_name)

positions = np.array([xs, ys, zs], dtype=np.float32).T
charges_np = np.array(charges, dtype=np.float32)
elements_np = np.array(elements, dtype=np.int32)
aromatic_np = np.array(aromatics, dtype=np.float32)
pos_ion_np = np.array(pos_ions, dtype=np.float32)
neg_ion_np = np.array(neg_ions, dtype=np.float32)
zn_binder_np = np.array(zn_binders, dtype=np.float32)
atom_names_np = np.array(atom_names)
num_atoms = positions.shape[0]
print(f"  -> Parsed {num_atoms} atoms directly from text.")

# ==========================================
# Pre-tag Hydrogen-Bond Donors (native NumPy/SciPy geometry)
# ==========================================
# A Nitrogen (7) or Oxygen (8) is flagged as a donor when it carries a
# covalently bound Hydrogen (1) within 1.2 Angstroms.
donor_np = np.zeros(num_atoms, dtype=np.float32)
h_mask = elements_np == 1
heavy_mask = (elements_np == 7) | (elements_np == 8) | (elements_np == 16)
if h_mask.any() and heavy_mask.any():
    h_tree = cKDTree(positions[h_mask])
    heavy_idx = np.where(heavy_mask)[0]
    # Distance to the nearest hydrogen; inf when none is within 1.2 A.
    dist, _ = h_tree.query(positions[heavy_idx], k=1, distance_upper_bound=1.2)
    donor_np[heavy_idx[np.isfinite(dist)]] = 1.0

print(f"  -> Tagged {int(aromatic_np.sum())} aromatic ring atoms "
      f"and {int(donor_np.sum())} H-bond donors.")

# Pre-tag Acceptors (Vectorized)
acceptor_np = np.zeros(num_atoms, dtype=np.float32)

# Rule A: Oxygens with negative charge
o_acc_mask = (elements_np == 8) & (charges_np <= -0.25)
acceptor_np[o_acc_mask] = 1.0

# Rule B: Nitrogens with negative charge, NO attached hydrogens, and NOT backbone 'N'
n_acc_mask = (elements_np == 7) & (charges_np <= -0.25) & (donor_np == 0.0) & (atom_names_np != 'N')
acceptor_np[n_acc_mask] = 1.0

# Pre-tag Hydrophobes (Vectorized)
# Rule: Carbon (6) or Sulfur (16) AND abs(charge) <= 0.2 AND NOT aromatic
hydro_mask = ((elements_np == 6) | (elements_np == 16)) & (np.abs(charges_np) <= 0.2) & (aromatic_np == 0.0)

hydrophobe_np = np.zeros(num_atoms, dtype=np.float32)
hydrophobe_np[hydro_mask] = 1.0

# ==========================================
# Push all flat arrays to GPU VRAM
# ==========================================
start_gpu = time.time()

real_x_gpu = cp.asarray(positions[:, 0], dtype=cp.float32)
real_y_gpu = cp.asarray(positions[:, 1], dtype=cp.float32)
real_z_gpu = cp.asarray(positions[:, 2], dtype=cp.float32)

# Biophysically accurate feature arrays (all synchronized 1:1 with coordinates):
real_charges_gpu = cp.asarray(charges_np, dtype=cp.float32)
real_elements_gpu = cp.asarray(elements_np, dtype=cp.int32)
real_donor_gpu = cp.asarray(donor_np, dtype=cp.float32)
real_acceptor_gpu = cp.asarray(acceptor_np, dtype=cp.float32)
real_hydrophobe_gpu = cp.asarray(hydrophobe_np, dtype=cp.float32)
real_aromatic_gpu = cp.asarray(aromatic_np, dtype=cp.float32)
real_pos_ion_gpu = cp.asarray(pos_ion_np, dtype=cp.float32)
real_neg_ion_gpu = cp.asarray(neg_ion_np, dtype=cp.float32)
real_zn_binder_gpu = cp.asarray(zn_binder_np, dtype=cp.float32)

cp.cuda.Device(0).synchronize()
transfer_ms = (time.time() - start_gpu) * 1000
total_ms = (time.time() - start_parse) * 1000

print("  -> GPU Transfer Complete! Ready for spatial hashing.")
print(f"  -> Pushed {num_atoms} atoms to VRAM in {transfer_ms:.4f} ms "
      f"(total parse+transfer {total_ms:.2f} ms).")

"""### 2. GPU Spatial Hashing and Grid Construction
* **Bounding Box Setup:** To avoid calculating the distance between every single atom and every single surface point ($O(N^2)$ complexity), the code creates a 3D bounding box with a 4.0 Ångstrom resolution grid around the protein.
* **Custom CUDA Kernels:** Compiles raw C++ CUDA kernels (`calc_hash` and `find_cell_bounds`) to quickly assign every atom to a grid cell and locate the start/end index of each cell after sorting.
* **Coupled Physics Reordering:** Once `sorted_order = cp.argsort(grid_hash_gpu)` is computed, *every* per-atom array parsed in Step 1 — coordinates, AMBER charges, element IDs, and the pre-tagged donor/aromatic flags — is reordered with that same mask. This keeps the geometric physics perfectly coupled to the spatial grid before it reaches the feature-aggregation kernel.

"""

# ==========================================
#@title Step 2. GPU Bounding Box, Compile C++ CUDA kernels & GPU Spatial Hashing
# ==========================================
print("\n2. Executing Step 2: Spatial Hashing and Grid Construction...")
start_step_2 = time.time()

CELL_SIZE = 4.0  # 4 Angstrom resolution grid

# Real PDB coordinates can be negative or offset from the origin.
# We find the absolute boundaries and shift the coordinates so they start at (0,0,0)
min_x, max_x = float(cp.min(real_x_gpu)), float(cp.max(real_x_gpu))
min_y, max_y = float(cp.min(real_y_gpu)), float(cp.max(real_y_gpu))
min_z, max_z = float(cp.min(real_z_gpu)), float(cp.max(real_z_gpu))

shift_x_gpu = real_x_gpu - min_x
shift_y_gpu = real_y_gpu - min_y
shift_z_gpu = real_z_gpu - min_z

# Calculate exact grid dimensions for this specific protein topology
GRID_DIM_X = int((max_x - min_x) // CELL_SIZE) + 1
GRID_DIM_Y = int((max_y - min_y) // CELL_SIZE) + 1
GRID_DIM_Z = int((max_z - min_z) // CELL_SIZE) + 1
TOTAL_CELLS = GRID_DIM_X * GRID_DIM_Y * GRID_DIM_Z

print(f"  -> Protein Span: X({min_x:.1f} to {max_x:.1f}), Y({min_y:.1f} to {max_y:.1f}), Z({min_z:.1f} to {max_z:.1f})")
print(f"  -> Generated 3D Uniform Grid Dimensions: {GRID_DIM_X} x {GRID_DIM_Y} x {GRID_DIM_Z} ({TOTAL_CELLS:,} total cells)")

# Compile Hashing Kernels
hashing_source = r'''
extern "C" {
    __global__ void calc_hash(const float* x, const float* y, const float* z,
                              int* grid_hash, int* original_indices,
                              float cell_size, int grid_dim_x, int grid_dim_y, int num_atoms) {
        int idx = blockDim.x * blockIdx.x + threadIdx.x;
        if (idx < num_atoms) {
            int cx = floor(x[idx] / cell_size);
            int cy = floor(y[idx] / cell_size);
            int cz = floor(z[idx] / cell_size);
            int hash = cx + (cy * grid_dim_x) + (cz * grid_dim_x * grid_dim_y);
            grid_hash[idx] = hash;
            original_indices[idx] = idx;
        }
    }

    __global__ void find_cell_bounds(const int* sorted_hashes, int* cell_starts, int* cell_ends, int num_atoms) {
        int idx = blockDim.x * blockIdx.x + threadIdx.x;
        if (idx < num_atoms) {
            int current_hash = sorted_hashes[idx];
            if (idx == 0) {
                cell_starts[current_hash] = idx;
            } else {
                int previous_hash = sorted_hashes[idx - 1];
                if (current_hash != previous_hash) {
                    cell_starts[current_hash] = idx;
                    cell_ends[previous_hash] = idx;
                }
            }
            if (idx == num_atoms - 1) {
                cell_ends[current_hash] = num_atoms;
            }
        }
    }
}
'''
hash_module = cp.RawModule(code=hashing_source)
calc_hash_kernel = hash_module.get_function('calc_hash')
find_cell_bounds_kernel = hash_module.get_function('find_cell_bounds')

# Allocate arrays for spatial index
grid_hash_gpu = cp.zeros(num_atoms, dtype=cp.int32)
original_indices_gpu = cp.zeros(num_atoms, dtype=cp.int32)
cell_starts_gpu = cp.full(TOTAL_CELLS, -1, dtype=cp.int32)
cell_ends_gpu = cp.full(TOTAL_CELLS, -1, dtype=cp.int32)

threads_per_block = 256
blocks_per_grid = (num_atoms + threads_per_block - 1) // threads_per_block

# Run Hashing Pipeline
calc_hash_kernel((blocks_per_grid,), (threads_per_block,),
                 (shift_x_gpu, shift_y_gpu, shift_z_gpu, grid_hash_gpu, original_indices_gpu,
                  np.float32(CELL_SIZE), GRID_DIM_X, GRID_DIM_Y, num_atoms))

sorted_order = cp.argsort(grid_hash_gpu)
sorted_hashes = grid_hash_gpu[sorted_order]

find_cell_bounds_kernel((blocks_per_grid,), (threads_per_block,),
                        (sorted_hashes, cell_starts_gpu, cell_ends_gpu, num_atoms))

# Reorder atomic coordinates to match the spatial grid optimization
sorted_x_gpu = shift_x_gpu[sorted_order]
sorted_y_gpu = shift_y_gpu[sorted_order]
sorted_z_gpu = shift_z_gpu[sorted_order]

# ---> Reorder ALL physics arrays with the exact same spatial mask so that
#      charges, elements, donor and aromatic tags stay coupled to the grid. <---
sorted_charges_gpu = real_charges_gpu[sorted_order]
sorted_elements_gpu = real_elements_gpu[sorted_order]
sorted_donor_gpu = real_donor_gpu[sorted_order]
sorted_acceptor_gpu = real_acceptor_gpu[sorted_order]
sorted_hydrophobe_gpu = real_hydrophobe_gpu[sorted_order]
sorted_aromatic_gpu = real_aromatic_gpu[sorted_order]
sorted_pos_ion_gpu = real_pos_ion_gpu[sorted_order]
sorted_neg_ion_gpu = real_neg_ion_gpu[sorted_order]
sorted_zn_binder_gpu = real_zn_binder_gpu[sorted_order]

cp.cuda.Device(0).synchronize()
end_step_2 = time.time()
print(f"  -> Step 2 (Spatial Hashing) took {(end_step_2 - start_step_2):.4f} seconds")

"""### 3. Surface Simulation and Native Geometric Feature Extraction
* **SAS Generation:** Simulates a Solvent-Accessible Surface (SAS) by generating 500,000 spatial sample points within the protein bounding box.
* **Native Pharmacophore Perception:** A custom CUDA kernel (`aggregate_features`) aggregates localized biochemical features for each point. Instead of RDKit SMARTS matching, the kernel perceives pharmacophores geometrically from the flat arrays produced in Step 1. Within the 4.0 Ångstrom cutoff (and using distance weighting `w = 1 / (1 + d)`) it accumulates, per surface point: neighbor atom count, Coulombic electrostatic potential, and the densities of **H-bond acceptors** (electronegative N/O with charge < −0.3), **H-bond donors** (pre-tagged N/O–H atoms), **hydrophobes** (near-neutral carbons), and **aromatics** (pre-tagged ring atoms).
* **Steric Rejection:** Points that fall inside the protein volume (within the steric cutoff of any atom) are discarded so only true surface points survive.

I updated the custom CUDA kernel in the feature-extraction cell in two ways. First, a `steric_cutoff` (set to 2.5 Ångstroms, representing the combined radii of an atom and a water-molecule probe) lets the GPU dynamically flag and reject any generated points that fall inside the protein's surface volume, effectively simulating a true Solvent-Accessible Surface without internal steric clashes.

Second, the kernel now performs native geometric pharmacophore perception directly inside the distance-checking loop — computing H-bond acceptor, H-bond donor, hydrophobe, and aromatic densities from the element/charge/donor/aromatic arrays — so RDKit is no longer needed to characterise the protein target.
"""

#@title Step 3: Localized SAS Generation & Native Geometric Feature Extraction
# ==========================================================================
# This cell generates the Solvent-Accessible Surface (SAS) sample points and
# runs the enriched CUDA aggregation kernel. The kernel now performs native
# geometric pharmacophore perception (acceptors, donors, hydrophobes,
# aromatics) directly from the flat physics arrays produced in Step 1 - no
# RDKit SMARTS matching is involved anywhere in the hot path.
# ==========================================================================
import time
import cupy as cp
import numpy as np

# ==========================================
# STEP 3: Localized SAS Generation & Feature Extraction
# ==========================================
print("\n3. Executing Step 3: Localized SAS Generation & Feature Extraction...")
start_step_3 = time.time()

# The physics arrays were already reordered by the spatial-hash sort in Step 2,
# so they stay perfectly aligned with sorted_x/y/z_gpu (the grid layout).
atom_charges_gpu = sorted_charges_gpu     # AMBER partial charges
atom_elements_gpu = sorted_elements_gpu   # atomic numbers (int32)
atom_donor_gpu = sorted_donor_gpu         # pre-tagged H-bond donors
atom_acceptor_gpu = sorted_acceptor_gpu   # pre-tagged H-bond acceptors
atom_hydrophobe_gpu = sorted_hydrophobe_gpu # pre-tagged hydrophobes
atom_aromatic_gpu = sorted_aromatic_gpu   # pre-tagged aromatic ring atoms
atom_pos_ion_gpu = sorted_pos_ion_gpu     # pre-tagged positive ionizable centers
atom_neg_ion_gpu = sorted_neg_ion_gpu     # pre-tagged negative ionizable centers
atom_zn_binder_gpu = sorted_zn_binder_gpu # pre-tagged zinc-binding atoms

# Generate mock Solvent-Accessible Surface points bounded tightly to the real
# protein dimensions. (These sample the search volume; steric clashes with the
# protein interior are rejected inside the kernel.)
NUM_SAS_POINTS = 500_000
sas_x_gpu = cp.random.uniform(0, max_x - min_x, NUM_SAS_POINTS, dtype=cp.float32)
sas_y_gpu = cp.random.uniform(0, max_y - min_y, NUM_SAS_POINTS, dtype=cp.float32)
sas_z_gpu = cp.random.uniform(0, max_z - min_z, NUM_SAS_POINTS, dtype=cp.float32)

# Allocate output tensors for the engineered pocket features.
f_counts = cp.zeros(NUM_SAS_POINTS, dtype=cp.float32)      # neighbor atom count
f_electro = cp.zeros(NUM_SAS_POINTS, dtype=cp.float32)     # Coulombic potential
f_acceptor = cp.zeros(NUM_SAS_POINTS, dtype=cp.float32)    # H-bond acceptor density
f_donor = cp.zeros(NUM_SAS_POINTS, dtype=cp.float32)       # H-bond donor density
f_hydrophobe = cp.zeros(NUM_SAS_POINTS, dtype=cp.float32)  # hydrophobe density
f_aromatic = cp.zeros(NUM_SAS_POINTS, dtype=cp.float32)    # aromatic density
f_pos_ion = cp.zeros(NUM_SAS_POINTS, dtype=cp.float32)     # positive ionizable density
f_neg_ion = cp.zeros(NUM_SAS_POINTS, dtype=cp.float32)     # negative ionizable density
f_zn_binder = cp.zeros(NUM_SAS_POINTS, dtype=cp.float32)   # zinc-binder density
f_density = cp.zeros(NUM_SAS_POINTS, dtype=cp.float32)     # buriedness (atoms per cubic Angstrom)

# Compile the Enriched Feature Aggregation Kernel with native pharmacophore logic.
aggregation_source = r'''
extern "C" __global__
void aggregate_features(const float* sas_x, const float* sas_y, const float* sas_z,
                        const float* atom_x, const float* atom_y, const float* atom_z,
                        const float* atom_charges, const int* atom_elements,
                        const float* atom_is_donor, const float* atom_is_acceptor,
                        const float* atom_is_hydrophobe, const float* atom_is_aromatic,
                        const float* atom_is_pos_ion, const float* atom_is_neg_ion,
                        const float* atom_is_zn_binder,
                        const int* cell_starts, const int* cell_ends,
                        float* out_counts, float* out_electro,
                        float* out_acceptor, float* out_donor,
                        float* out_hydrophobe, float* out_aromatic,
                        float* out_pos_ion, float* out_neg_ion, float* out_zn_binder,
                        float* out_density,
                        float cell_size, float cutoff, float steric_cutoff,
                        int grid_dim_x, int grid_dim_y, int grid_dim_z, int num_sas) {

    int idx = blockDim.x * blockIdx.x + threadIdx.x;
    if (idx >= num_sas) return;

    float sx = sas_x[idx]; float sy = sas_y[idx]; float sz = sas_z[idx];
    int scx = floor(sx / cell_size); int scy = floor(sy / cell_size); int scz = floor(sz / cell_size);

    float c_count = 0.0f; float c_electro = 0.0f;
    float c_acceptor = 0.0f; float c_donor = 0.0f;
    float c_hydrophobe = 0.0f; float c_aromatic = 0.0f;
    float c_pos_ion = 0.0f; float c_neg_ion = 0.0f; float c_zn_binder = 0.0f;

    float cutoff_sq = cutoff * cutoff;
    float steric_cutoff_sq = steric_cutoff * steric_cutoff;
    bool clashing = false;

    for (int dz = -1; dz <= 1; ++dz) {
        for (int dy = -1; dy <= 1; ++dy) {
            for (int dx = -1; dx <= 1; ++dx) {
                int cx = scx + dx; int cy = scy + dy; int cz = scz + dz;
                if (cx >= 0 && cx < grid_dim_x && cy >= 0 && cy < grid_dim_y && cz >= 0 && cz < grid_dim_z) {
                    int hash = cx + (cy * grid_dim_x) + (cz * grid_dim_x * grid_dim_y);
                    int start_idx = cell_starts[hash];
                    if (start_idx != -1) {
                        int end_idx = cell_ends[hash];
                        for (int a_idx = start_idx; a_idx < end_idx; ++a_idx) {
                            float dx_a = sx - atom_x[a_idx];
                            float dy_a = sy - atom_y[a_idx];
                            float dz_a = sz - atom_z[a_idx];
                            float d_sq = dx_a*dx_a + dy_a*dy_a + dz_a*dz_a;

                            if (d_sq < steric_cutoff_sq) {
                                clashing = true;
                            }

                            if (!clashing && d_sq <= cutoff_sq && d_sq > 0.001f) {
                                float d = sqrtf(d_sq);
                                float w = 1.0f / (1.0f + d);

                                int   elem        = atom_elements[a_idx];
                                float chg         = atom_charges[a_idx];
                                float is_donor    = atom_is_donor[a_idx];
                                float is_acceptor = atom_is_acceptor[a_idx];
                                float is_hydrophobe = atom_is_hydrophobe[a_idx];
                                float is_aromatic = atom_is_aromatic[a_idx];
                                float is_pos_ion  = atom_is_pos_ion[a_idx];
                                float is_neg_ion  = atom_is_neg_ion[a_idx];
                                float is_zn_binder = atom_is_zn_binder[a_idx];

                                c_count += 1.0f;
                                c_electro += chg * (1.0f / d);

                                // --- Native geometric pharmacophore perception ---
                                // Instead of evaluating elements and charges for acceptors in C++,
                                // just read the pre-tagged array we built in Python:
                                if (is_acceptor == 1.0f) { c_acceptor += w; }
                                if (is_donor == 1.0f) { c_donor += w; }
                                if (is_hydrophobe == 1.0f) { c_hydrophobe += w; }
                                if (is_aromatic == 1.0f) { c_aromatic += w; }
                                if (is_pos_ion == 1.0f) { c_pos_ion += w; }
                                if (is_neg_ion == 1.0f) { c_neg_ion += w; }
                                if (is_zn_binder == 1.0f) { c_zn_binder += w; }
                            }
                        }
                    }
                }
            }
        }
    }

    if (clashing) {
        out_counts[idx] = 0.0f; out_electro[idx] = 0.0f;
        out_acceptor[idx] = 0.0f; out_donor[idx] = 0.0f;
        out_hydrophobe[idx] = 0.0f; out_aromatic[idx] = 0.0f;
        out_pos_ion[idx] = 0.0f; out_neg_ion[idx] = 0.0f; out_zn_binder[idx] = 0.0f;
        out_density[idx] = 0.0f;
    } else {
        out_counts[idx] = c_count; out_electro[idx] = c_electro;
        out_acceptor[idx] = c_acceptor; out_donor[idx] = c_donor;
        out_hydrophobe[idx] = c_hydrophobe; out_aromatic[idx] = c_aromatic;
        out_pos_ion[idx] = c_pos_ion; out_neg_ion[idx] = c_neg_ion; out_zn_binder[idx] = c_zn_binder;

        // --- Buriedness / Solid Angle proxy ---
        // Convert the raw neighbor atom count into a local density (atoms per cubic
        // Angstrom) inside the 4.0 A probe sphere. A point on a flat surface only sees
        // protein in ~half the sphere (low density), whereas a point deep inside a
        // cavity is almost fully enclosed by protein (high density). Feeding this ratio
        // to XGBoost teaches it to favor physically enclosed, buried pockets over flat
        // surfaces.
        float sphere_volume = (4.0f / 3.0f) * 3.14159265358979f * cutoff * cutoff * cutoff;
        out_density[idx] = c_count / sphere_volume;
    }
}
'''
agg_module = cp.RawModule(code=aggregation_source)
aggregate_kernel = agg_module.get_function('aggregate_features')

CUTOFF_RADIUS = 4.0
STERIC_CUTOFF = 2.5  # ~1.5A VDW radius + 1.0A probe (prevents interior clashing)
sas_blocks = (NUM_SAS_POINTS + threads_per_block - 1) // threads_per_block

cp.cuda.Device(0).synchronize()
start_kernel_time = time.time()

aggregate_kernel((sas_blocks,), (threads_per_block,),
                 (sas_x_gpu, sas_y_gpu, sas_z_gpu, sorted_x_gpu, sorted_y_gpu, sorted_z_gpu,
                  atom_charges_gpu, atom_elements_gpu, atom_donor_gpu, atom_acceptor_gpu, atom_hydrophobe_gpu, atom_aromatic_gpu,
                  atom_pos_ion_gpu, atom_neg_ion_gpu, atom_zn_binder_gpu,
                  cell_starts_gpu, cell_ends_gpu,
                  f_counts, f_electro, f_acceptor, f_donor, f_hydrophobe, f_aromatic,
                  f_pos_ion, f_neg_ion, f_zn_binder,
                  f_density,
                  np.float32(CELL_SIZE), np.float32(CUTOFF_RADIUS), np.float32(STERIC_CUTOFF),
                  GRID_DIM_X, GRID_DIM_Y, GRID_DIM_Z, NUM_SAS_POINTS))

cp.cuda.Device(0).synchronize()
end_kernel_time = time.time()
end_step_3 = time.time()

# ==========================================
# 4. Diagnostics and Validation
# ==========================================
print(f"  -> Kernel execution completed in {(end_kernel_time - start_kernel_time)*1000:.2f} ms")
print(f"  -> Step 3 (Feature Extraction) took {(end_step_3 - start_step_3):.4f} seconds")

# Pull out points that successfully intercepted the protein's surface fold.
valid_points = cp.where(f_counts > 0)[0]
print(f"  -> Total SAS points cleanly intersecting protein environment (no clashes): {len(valid_points):,} / {NUM_SAS_POINTS:,}")

if len(valid_points) > 0:
    sample_idx = valid_points[0].item()
    print(f"\nExemplar Surface Descriptor Vector (Point Index {sample_idx:05d}):")
    print(f"  * Neighboring Atom Count within 4A: {f_counts[sample_idx].item()}")
    print(f"  * Local Electrostatic Potential (Coulombic): {f_electro[sample_idx].item():.4f}")
    print(f"  * Local H-Bond Acceptor Density: {f_acceptor[sample_idx].item():.4f}")
    print(f"  * Local H-Bond Donor Density: {f_donor[sample_idx].item():.4f}")
    print(f"  * Local Hydrophobe Density: {f_hydrophobe[sample_idx].item():.4f}")
    print(f"  * Local Aromatic Density: {f_aromatic[sample_idx].item():.4f}")
    print(f"  * Local Positive Ionizable Density: {f_pos_ion[sample_idx].item():.4f}")
    print(f"  * Local Negative Ionizable Density: {f_neg_ion[sample_idx].item():.4f}")
    print(f"  * Local Zinc-Binder Density: {f_zn_binder[sample_idx].item():.4f}")
    print(f"  * Local Buriedness (atoms/A^3 in 4A sphere): {f_density[sample_idx].item():.4f}")

"""To visualize the impact of moving from random noise to true AMBER electrostatics, you should make two primary adjustments to your py3Dmol visualization cell:

Load the .pqr File Instead of the .pdb File: Since py3Dmol natively understands the PQR format, it automatically maps the AMBER partial charges into its internal atom data array (specifically under the b or temperature factor property).

Generate an Electrostatic Molecular Surface: By applying a Red-White-Blue (rwb) color gradient to the molecular surface based on those native PQR charges, you can visually inspect the true electrostatic environment of the pocket.

**Point Index:** This refers to the specific ID of one of the 500,000 simulated Solvent-Accessible Surface (SAS) points generated around the protein. For example, "Point Index 3" simply means it was the 4th point randomly generated in that massive array of points.

**GPU Spatial Grid Box:** This is a 3D sub-volume (a 4.0 Ångstrom "voxel" or cube) used in the spatial hashing algorithm. The entire bounding box is divided into thousands of these grid cells so the GPU can quickly find neighboring atoms without having to check the distance to every single atom in the protein.

In short: the point index identifies a specific **simulated surface particle**, while a grid box identifies a specific **region of 3D space** used to accelerate the math.
"""

#@title Py3DMol visualisation of GPU Bounding Box & Spatial Hashing
import py3Dmol
import cupy as cp

# Extract valid SAS points (those with neighbor counts > 0)
# It uses cp.where(f_counts > 0) to filter out only the simulated points that successfully found neighbors (intersected the protein). It then shifts their coordinates back to the real-world scale and pulls the data from the GPU back to the CPU using .get().
valid_points = cp.where(f_counts > 0)[0]
true_x = (sas_x_gpu[valid_points] + min_x).get()
true_y = (sas_y_gpu[valid_points] + min_y).get()
true_z = (sas_z_gpu[valid_points] + min_z).get()

# Create an XYZ string for the SAS points for efficient rendering
# It converts these coordinates into a raw XYZ string format, treating each point as an Oxygen atom (O). This allows the 3D viewer to ingest the massive number of points efficiently.
num_points = len(true_x)
xyz_data = f"{num_points}\nSAS points\n"
xyz_data += "\n".join([f"O {x:.3f} {y:.3f} {z:.3f}" for x, y, z in zip(true_x, true_y, true_z)])

# Initialize viewer
view = py3Dmol.view(width=800, height=600)

# Add protein (Model 0)
with open("/content/5RMM_prepared.pqr", "r") as f:
    view.addModel(f.read(), "pqr")

# Set default style to a combination of cartoon and thin sticks
view.setStyle({'model': 0}, {'cartoon': {'color': 'lightgray'}, 'stick': {'radius': 0.15}})

# Explicitly set hydrogen atoms to white sticks
view.addStyle({'elem': 'H', 'model': 0}, {'stick': {'color': 'white', 'radius': 0.1}})

# Add the True AMBER Electrostatic Surface
view.addSurface(py3Dmol.VDW, {
    'opacity': 0.70,
    'colorscheme': {
        'prop': 'partialCharge',
        'gradient': 'rwb',
        'min': -0.5,
        'max': 0.5
    }
}, {'model': 0})

# Add SAS points (Model 1)
#It loads the generated XYZ string and styles those points as small green spheres representing the localized surface.
view.addModel(xyz_data, "xyz")
view.setStyle({'model': 1}, {'sphere': {'color': 'lightgreen', 'radius': 0.4, 'opacity': 0.7}})

if len(valid_points) > 0:
    sample_idx = valid_points[0].item()
    ex_x = float((sas_x_gpu[sample_idx] + min_x).item())
    ex_y = float((sas_y_gpu[sample_idx] + min_y).item())
    ex_z = float((sas_z_gpu[sample_idx] + min_z).item())
    label_text = (
        f"Point Index: {sample_idx}\n"
        f"Neighbors: {f_counts[sample_idx].item()}\n"
        f"Electro: {f_electro[sample_idx].item():.4f}\n"
        f"Acceptor: {f_acceptor[sample_idx].item():.4f}\n"
        f"Donor: {f_donor[sample_idx].item():.4f}\n"
        f"Hydrophobe: {f_hydrophobe[sample_idx].item():.4f}\n"
        f"Aromatic: {f_aromatic[sample_idx].item():.4f}"
    )
    view.addLabel(label_text, {'position': {'x': ex_x, 'y': ex_y, 'z': ex_z}, 'backgroundColor': 'black', 'backgroundOpacity': 0.7, 'fontColor': 'white'})
    view.zoomTo({'model': 0})
else:
    view.zoomTo({'model': 0})

# Add GPU Bounding Box as a cyan wireframe
view.addBox({
    'center': {'x': (min_x + max_x) / 2, 'y': (min_y + max_y) / 2, 'z': (min_z + max_z) / 2},
    'dimensions': {'w': max_x - min_x, 'h': max_y - min_y, 'd': max_z - min_z},
    'color': 'cyan',
    'wireframe': True
})

# Calculate exact grid boundaries used in GPU hashing
#It mathematically reconstructs the computational 3D grid you created on the GPU (Step 2) and uses loops to draw cyan wireframe lines representing the bounding box and individual grid cells.
grid_max_x = min_x + GRID_DIM_X * CELL_SIZE
grid_max_y = min_y + GRID_DIM_Y * CELL_SIZE
grid_max_z = min_z + GRID_DIM_Z * CELL_SIZE

# Add Grid Cells as magenta lines
for j in range(GRID_DIM_Y + 1):
    for k in range(GRID_DIM_Z + 1):
        view.addLine({'start': {'x': min_x, 'y': min_y + j * CELL_SIZE, 'z': min_z + k * CELL_SIZE},
                      'end': {'x': grid_max_x, 'y': min_y + j * CELL_SIZE, 'z': min_z + k * CELL_SIZE},
                      'color': 'cyan'})

for i in range(GRID_DIM_X + 1):
    for k in range(GRID_DIM_Z + 1):
        view.addLine({'start': {'x': min_x + i * CELL_SIZE, 'y': min_y, 'z': min_z + k * CELL_SIZE},
                      'end': {'x': min_x + i * CELL_SIZE, 'y': grid_max_y, 'z': min_z + k * CELL_SIZE},
                      'color': 'cyan'})

for i in range(GRID_DIM_X + 1):
    for j in range(GRID_DIM_Y + 1):
        view.addLine({'start': {'x': min_x + i * CELL_SIZE, 'y': min_y + j * CELL_SIZE, 'z': min_z},
                      'end': {'x': min_x + i * CELL_SIZE, 'y': min_y + j * CELL_SIZE, 'z': grid_max_z},
                      'color': 'cyan'})

print(f"Displaying {num_points} SAS points intersecting the protein environment, along with the GPU grid.")
view.show()

"""The 3D visualization cell executed successfully. In the output, you should now see your protein with a beautiful Red-White-Blue electrostatic surface, driven entirely by the genuine AMBER charges. The specific points representing the maximum and minimum electrostatic potentials, as well as the maximum aromatic density, are also explicitly labeled.

### 4. GPU-Accelerated Machine Learning (XGBoost Regression Model)

This code cell handles the machine learning portion of the pipeline. Here is a breakdown of what it does:

1. **Feature Matrix Construction:** It stacks the 9 previously calculated biophysical and geometric features (like neighbor counts, electrostatic potential, and donor/acceptor densities) into a single large matrix (`X_gpu`). It then filters this matrix to keep only the points that successfully intersected the protein surface.

2. **GPU Model Initialization:** It initializes an XGBoost Regression model. The key here is the use of `tree_method='hist'` and `device='cuda'`. These parameters instruct the model to perform all computations natively on the GPU's CUDA cores, entirely avoiding slow transfers between the CPU and GPU.

3. **Mock Target Generation:** Because this is a proof-of-concept without real fragment-bound data, it randomly generates a target array (`Y_train_gpu`) of 0s and 1s. This acts as a simulated 'ground truth' for whether a point is a pocket or not.

4. **Model Training and Saving:** It trains the model using the zero-copy CuPy arrays and then saves the resulting trained weights to a file named `xgboost_pocket_weights.pkl` for later use.
"""

#@title XGBoost Model Training
import xgboost as xgb
import cupy as cp
import pickle
import time

# ==========================================
# 0. Construct the Feature Matrix
# ==========================================
# Full feature matrix for later inference
X_gpu = cp.column_stack((
    f_counts,      # local atom density
    f_electro,     # Coulombic electrostatic potential (AMBER)
    f_acceptor,    # H-bond acceptor pharmacophore density
    f_donor,       # H-bond donor pharmacophore density
    f_hydrophobe,  # hydrophobe pharmacophore density
    f_aromatic,    # aromatic pharmacophore density
    f_pos_ion,     # positive ionizable pharmacophore density
    f_neg_ion,     # negative ionizable pharmacophore density
    f_zn_binder,   # zinc-binder pharmacophore density
    f_density      # buriedness: local atom density (atoms per cubic Angstrom)
))

# Filter to only the valid SAS points (those intersecting the protein)
valid_points = cp.where(f_counts > 0)[0]
X_train_gpu = X_gpu[valid_points]

# ==========================================
# 1. Initialize the GPU-Accelerated XGBoost Model
# ==========================================
# The parameters 'tree_method="hist"' and 'device="cuda"' are the magic keys.
# They tell XGBoost to never move the data to the CPU, running all gradient mathematics natively on the GPU cores.

xgb_model = xgb.XGBRegressor(
    n_estimators=300,        # Number of sequential trees
    max_depth=8,             # How deep each tree can look into feature interactions
    learning_rate=0.05,      # How aggressively the next tree corrects the previous one
    tree_method='hist',      # Highly optimized histogram binning for GPUs
    device='cuda'            # Execute on GPU
)

# ==========================================
# 2. Train the Model (Knowledge Distillation)
# ==========================================
print(f"Training XGBoost on GPU using {len(valid_points):,} valid solvent-accessible surface (SAS) points...")
start_train = time.time()

# Create a mock target array to simulate the training phase for the valid points
Y_train_gpu = cp.random.choice([0, 1], size=X_train_gpu.shape[0]).astype(cp.float32)

# XGBoost accepts CuPy arrays directly! Zero-copy transfer.
xgb_model.fit(X_train_gpu, Y_train_gpu)

print(f"Training completed in {(time.time() - start_train):.2f} seconds")

# Save the custom weights
with open("xgboost_pocket_weights.pkl", "wb") as f:
    pickle.dump(xgb_model, f)

    print(f"The model weights have been saved to xgboost_pocket_weights.pkl")

"""### 5. GPU-Accelerated XGBoost Inference

* **Inference:** Using simulated target data, the model predicts **"ligandability scores"** (the probability that a point belongs to a binding pocket) for the entire feature matrix:

* This cell performs the actual prediction (inference) using the trained XGBoost model and simulated target data. It takes the entire feature matrix (`X_gpu`), which contains the biophysical properties of all 500,000 simulated surface points, and asks the model to predict a **'ligandability score'** (the probability that a point belongs to a binding pocket)for each point.

* Because everything is kept as CuPy arrays, this prediction happens entirely on the GPU, making it extremely fast. The resulting scores are stored in `ligandability_scores_gpu` and will be used in the next step to cluster the highest-scoring points into distinct binding pockets.
"""

#@title XGBoost Model Inference
import xgboost as xgb
import cupy as cp
import pickle
import time

# ==========================================
# 3. Inference (Predicting new pockets)
# ==========================================
start_infer = time.time()

# Predict directly from the engineered feature matrix
predictions = xgb_model.predict(X_gpu)

# Ensure the output stays as a CuPy array for the DBSCAN step
ligandability_scores_gpu = cp.asarray(predictions, dtype=cp.float32)

print(f"XGBoost Inference completed in {(time.time() - start_infer)*1000:.2f} ms")

"""### 6. Pocket Clustering and Segmentation

This code performs pocket segmentation and clustering to identify distinct ligand-binding sites on the protein. Here is a step-by-step breakdown of what it does:

**Dynamic Filtering:** It filters the simulated surface points, keeping only the top 10% highest-scoring points (predicted by the XGBoost model) that physically intersect the protein.

**GPU Clustering (DBSCAN):** It uses the DBSCAN algorithm from the cuML library to spatially group these high-scoring candidate points. Points within 4.0 Ångstroms of each other are clustered into a single 'pocket', with a minimum of 10 points required to form a valid cluster. This runs entirely on the GPU for speed.

**Pocket Compilation and Ranking:** For each identified pocket, it calculates the geometric center (centroid) in 3D space and assigns a total score by summing the individual probabilities of all points within that pocket. The pockets are then sorted in descending order based on this score.

**Output:** Finally, it prints a ranked summary of the discovered pockets, detailing their rank, total score, surface point density, and 3D centroid coordinates.
"""

#@title Dynamic Filtering, GPU Clustering, and Pocket Ranking
import cupy as cp
import numpy as np
from cuml.cluster import DBSCAN
from scipy.spatial import ConvexHull
try:
    # Public location (scipy >= 1.8)
    from scipy.spatial import QhullError
except ImportError:
    # Fallback for older scipy releases
    from scipy.spatial.qhull import QhullError
import time

print("Executing Step 4: Pocket Segmentation and Spatial Clustering...")

# ==========================================
# 1. Retrieve the XGBoost Inference Scores
# ==========================================
# We are now using the `ligandability_scores_gpu` predicted natively by our XGBoost model

# ==========================================
# 2. Apply Probability Threshold Filter
# ==========================================
# Because the model was trained on random data, most scores hover around 0.5.
# A static threshold of 0.3 allows too many points through, creating one giant cluster.
# Instead, we dynamically take the top 10% of scoring points.
valid_scores = ligandability_scores_gpu[f_counts > 0]
SCORE_THRESHOLD = float(cp.percentile(valid_scores, 90))
print(f"Calculated 90th percentile threshold: {SCORE_THRESHOLD:.3f}")

# We find points that are both near the protein (f_counts > 0) AND have high ML scores
candidate_mask = (f_counts > 0) & (ligandability_scores_gpu >= SCORE_THRESHOLD)
candidate_indices = cp.where(candidate_mask)[0]

print(f"  -> Extracted {len(candidate_indices):,} high-probability candidate points (Score >= {SCORE_THRESHOLD:.3f})")

if len(candidate_indices) == 0:
    print("No points passed the threshold. Lowering threshold to 0.2 for simulation visibility...")
    candidate_mask = (f_counts > 0) & (ligandability_scores_gpu >= 0.2)
    candidate_indices = cp.where(candidate_mask)[0]

# Extract the physical 3D coordinates of the surviving points
# We subtract the shift to return them to the original, true PDB coordinate space
final_coords_gpu = cp.column_stack((
    sas_x_gpu[candidate_indices] + min_x,
    sas_y_gpu[candidate_indices] + min_y,
    sas_z_gpu[candidate_indices] + min_z
))
final_scores_gpu = ligandability_scores_gpu[candidate_indices]

# ==========================================
# 3. High-Performance GPU DBSCAN
# ==========================================
# Epsilon = 4.0 Angstroms (spatial search radius for grouping)
# Min_samples = 10 (at least 10 high-scoring points are needed to make a pocket)
EPSILON_RADIUS = 4.0
MIN_POCKET_POINTS = 10

dbscan_gpu = DBSCAN(eps=EPSILON_RADIUS, min_samples=MIN_POCKET_POINTS, output_type='cupy')

start_cluster = time.time()
# Run clustering natively in VRAM
cluster_labels_gpu = dbscan_gpu.fit_predict(final_coords_gpu)
end_cluster = time.time()

print(f"  -> DBSCAN segmentation completed on GPU in {(end_cluster - start_cluster)*1000:.2f} ms")

# ==========================================
# 4. Pocket Compilation, Volume Estimation, and Ranking
# ==========================================
# Labels of -1 indicate background noise points rejected by DBSCAN
unique_labels = cp.unique(cluster_labels_gpu)
pockets = []

# A true cavity is compact: it packs many surface points into a small enclosed
# volume. Sprawling, shallow clusters spread few points over a huge convex hull,
# giving a very low point density. We reject those below this cutoff (points/A^3).
MIN_POINT_DENSITY = 0.01  # surface points per cubic Angstrom
rejected_sprawling = 0

for label in unique_labels:
    if label == -1:
        continue # Skip noise

    pocket_mask = (cluster_labels_gpu == label)
    pocket_coords = final_coords_gpu[pocket_mask]
    pocket_scores = final_scores_gpu[pocket_mask]

    # Calculate the center of mass (geometric centroid) of the pocket
    centroid = cp.mean(pocket_coords, axis=0)
    # The total pocket score is the sum of its point probabilities
    total_score = cp.sum(pocket_scores).item()
    points_count = int(cp.sum(pocket_mask))

    # --- True cavity volume via Convex Hull (Voxel Inversion) ---
    # Pull the cluster's XYZ coordinates back to the CPU and wrap them in a convex
    # hull. ConvexHull(...).volume returns the enclosed geometric volume of the
    # pocket in cubic Angstroms. A ConvexHull needs at least 4 non-coplanar points;
    # degenerate (flat/collinear) clusters raise QhullError and are treated as
    # zero-volume so they can be filtered out.
    pocket_coords_cpu = cp.asnumpy(pocket_coords)
    try:
        pocket_volume = float(ConvexHull(pocket_coords_cpu).volume)
    except (QhullError, ValueError):
        pocket_volume = 0.0

    # Point density (compactness). Guard against division by zero for flat clusters.
    point_density = points_count / pocket_volume if pocket_volume > 0.0 else 0.0

    # Filter out sprawling, shallow clusters before they reach the export stage.
    if pocket_volume <= 0.0 or point_density < MIN_POINT_DENSITY:
        rejected_sprawling += 1
        continue

    pockets.append({
        'id': int(label),
        'centroid': centroid.tolist(),
        'points_count': points_count,
        'rank_score': total_score,
        'volume': pocket_volume,
        'point_density': point_density
    })

if rejected_sprawling > 0:
    print(f"  -> Filtered out {rejected_sprawling} sprawling/shallow cluster(s) "
          f"(volume <= 0 or density < {MIN_POINT_DENSITY} points/A^3)")

# Sort pockets by their cumulative score in descending order (matching P2Rank logic)
pockets = sorted(pockets, key=lambda k: k['rank_score'], reverse=True)

# ==========================================
# 5. Output Final Discovered Binding Sites
# ==========================================
print(f"\nDiscovered {len(pockets)} verified ligand-binding pockets on {pdb_id}:")
print("-" * 75)
for rank, pocket in enumerate(pockets):
    cx, cy, cz = pocket['centroid']
    print(f"RANK {rank + 1} (Internal Cluster ID: {pocket['id']})")
    print(f"  * Pocket Score: {pocket['rank_score']:.2f}")
    print(f"  * Density (Total Points): {pocket['points_count']} surface points")
    print(f"  * Cavity Volume (Convex Hull): {pocket['volume']:.2f} A^3")
    print(f"  * Point Density (compactness): {pocket['point_density']:.4f} points/A^3")
    print(f"  * Predicted Centroid (X, Y, Z): ({cx:.2f}, {cy:.2f}, {cz:.2f})")
    print("-" * 75)

"""### 7. Export and Final Visualization
* **Data Export:** The final pocket predictions—including ranks, scores, point densities, and XYZ centroid coordinates—are structured as a dictionary and exported to a JSON file (`5RMM_gpu_predictions.json`).
"""

#@title 8. Save GPU Pocket Predicitons
import json

# Create a list of dictionaries matching P2Rank's standard predictions output
output_data = []
for rank, pocket in enumerate(pockets):
    cx, cy, cz = pocket['centroid']
    output_data.append({
        'name': f'pocket{rank + 1}',
        'rank': rank + 1,
        'score': round(pocket['rank_score'], 3),
        'probability': round(pocket['rank_score'] / (pocket['points_count'] + 1e-5), 3), # Proxy for probability
        'center_x': round(cx, 3),
        'center_y': round(cy, 3),
        'center_z': round(cz, 3),
        'sas_points': pocket['points_count'],
        'volume': round(pocket['volume'], 3),  # enclosed cavity volume in cubic Angstroms
        'point_density': round(pocket['point_density'], 4)
    })

# Export to JSON
with open(f"{pdb_id}_gpu_predictions.json", "w") as f:
    json.dump(output_data, f, indent=4)

print(f"\nSuccessfully exported predictions to {pdb_id}_gpu_predictions.json")

#@title 9. Filter Top 5 Ranked Pockets, Save Residues
import pandas as pd
import json

pdb_id = "5RMM"
json_file = f"{pdb_id}_gpu_predictions.json"
pdb_file = f"{pdb_id}.pdb"
output_residues_file = f"{pdb_id}_pocket_residues.json"

# Read the predicted pockets from JSON
df = pd.read_json(json_file)

# Filter for top 5 ranked pockets
df = df.head(5)

# Parse PDB to extract Chain B atomic coordinates for distance calculations
chain_b_atoms = []
with open(pdb_file, 'r') as f:
    for line in f:
        if line.startswith('ATOM') and line[21] == 'B':
            res_name = line[17:20].strip()
            res_num = int(line[22:26].strip())
            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])
            chain_b_atoms.append((res_num, res_name, x, y, z))

print(f"Processing {len(df)} Ranked Pockets on Chain B.")

# Dictionary to store the residues for JSON export
pocket_residues_export = {}

# Process all ranked pockets
colors = ['red', 'blue', 'green', 'yellow', 'purple', 'cyan', 'orange', 'magenta']
for idx, row in df.iterrows():
    cx = float(row['center_x'])
    cy = float(row['center_y'])
    cz = float(row['center_z'])
    rank = int(row['rank'])

    # Cycle through colors for different pockets (Rank 1 is red)
    color = colors[idx % len(colors)]
    print(f"\nRank {rank} is represented by color: {color}")

    # Calculate and print residues within 8.0 Angstroms
    pocket_residues = set()
    for res_num, res_name, ax, ay, az in chain_b_atoms:
        dist_sq = (ax - cx)**2 + (ay - cy)**2 + (az - cz)**2
        if dist_sq <= 64.0: # 8.0 squared
            pocket_residues.add((res_num, res_name))

    res_strs = [f"{name}{num}" for num, name in sorted(list(pocket_residues))]
    print(f"  -> Residues within 8Å: {', '.join(res_strs)}")

    # Add to our export dictionary
    pocket_residues_export[f"Rank_{rank}"] = res_strs

# Export the collected residues to a JSON file
with open(output_residues_file, "w") as f:
    json.dump(pocket_residues_export, f, indent=4)
print(f"\nSaved pocket residues to {output_residues_file}")

"""* **Interactive 3D Rendering:** `py3Dmol` is used to load the original protein alongside the JSON predictions. The top 5 ranked pockets are mapped onto the protein model as distinct colored spheres, and the surrounding amino acids (within an 8.0 Ångstrom radius) are highlighted as stick models for structural context."""

#@title 10. Visualise Pocket Residues and Surface Meshes
import py3Dmol
import pandas as pd
import json

pdb_id = "5RMM"
json_file = f"{pdb_id}_gpu_predictions.json"
pqr_file = "/content/5RMM_prepared.pqr"
residues_file = "/content/5RMM_pocket_residues.json"

# Read the predicted pockets from JSON
df = pd.read_json(json_file)

# Filter for top 5 ranked pockets
df = df.head(5)

# Load the explicitly saved pocket residues
with open(residues_file, "r") as f:
    pocket_residues_dict = json.load(f)

# Initialize py3Dmol viewer
view = py3Dmol.view(width=800, height=600)

# Load the protein structure with hydrogens kept
with open(pqr_file, 'r') as f:
    view.addModel(f.read(), 'pqr', {'keepH': True})

# Explicitly clear all styles, then set cartoon for the whole model
view.setStyle({}, {})
view.addStyle({}, {'cartoon': {'color': 'white', 'opacity': 0.6}})

colors = ['red', 'blue', 'green', 'yellow', 'purple', 'cyan', 'orange', 'magenta']

for idx, row in df.iterrows():
    cx = float(row['center_x'])
    cy = float(row['center_y'])
    cz = float(row['center_z'])
    rank = int(row['rank'])

    # Use the same color rotation
    color = colors[idx % len(colors)]

    # Get residues from the loaded JSON
    res_list = pocket_residues_dict.get(f"Rank_{rank}", [])
    # Extract numeric residue IDs (ignoring the 3-letter amino acid code)
    res_nums = [int(r[3:]) for r in res_list]

    # Select the explicitly listed residues (removed chain constraint for PQR compatibility)
    if res_nums:
        pocket_sel = {'resi': res_nums}
    else:
        # Fallback if no residues were found in the JSON for this rank
        pocket_sel = {'within': {'distance': 8.0, 'sel': {'x': cx, 'y': cy, 'z': cz}}}

    # Highlight the residues as sticks with carbon colored by the pocket's designated color
    # This displays the explicit hydrogens for these specific residues (showHydrogens=true equivalent)
    view.addStyle(pocket_sel, {'stick': {'colorscheme': f'{color}Carbon', 'opacity': 1.0}})

    # Add mesh vdw surface to the pocket residues using electrostatic map gradient
    view.addSurface(py3Dmol.VDW, {
        'opacity': 0.6,
        'colorscheme': {'prop': 'partialCharge', 'gradient': 'rwb', 'min': -0.5, 'max': 0.5},
        'wireframe': True
    }, pocket_sel)

    # Add a label at the center
    view.addLabel(f"Pocket {rank}",
                  {'position': {'x': cx, 'y': cy, 'z': cz},
                   'backgroundColor': 'white',
                   'fontColor': color,
                   'backgroundOpacity': 0.8,
                   'fontSize': 14})

view.setBackgroundColor('white')
view.zoomTo()
view.show()

"""This code extracts and saves the chemical 'pharmacophore' features (like hydrogen bond donors, acceptors, or hydrophobic regions) specifically for the highest-ranked predicted pocket (Pocket 1). It first initializes RDKit's Feature Factory. Then, it loads the previously saved pocket residues to identify which amino acids make up Pocket 1. It loads the 3D protein structure and identifies the exact atom indices belonging to these residues. Next, it calculates all pharmacophore features for the entire protein, as RDKit requires full structural context. It then filters this massive list to keep only the features that physically overlap with Pocket 1. Finally, it exports these filtered features, including their 3D coordinates and chemical types, to a new JSON file for visualization."""

#@title Extract and save Pocket 1 Native Geometric Pharmacophore Features (RDKit-Free)
import json
import time
import numpy as np
from scipy.spatial import cKDTree

print("Step 1: Loading Pocket 1 residues from JSON...")
residues_file = '/content/5RMM_pocket_residues.json'
with open(residues_file, 'r') as f:
    pocket_residues_dict = json.load(f)

pocket1_res_strs = pocket_residues_dict.get("Rank_1", [])
p1_res_nums = set(int(r[3:]) for r in pocket1_res_strs)
print(f"  -> Found {len(p1_res_nums)} residues for Pocket 1.")

print("\nStep 2: Parsing PQR via text and identifying Native Geometric Pharmacophores...")
start_time = time.time()

AROMATIC_RING = {
    "PHE": {"CG", "CD1", "CD2", "CE1", "CE2", "CZ"},
    "TYR": {"CG", "CD1", "CD2", "CE1", "CE2", "CZ"},
    "TRP": {"CG", "CD1", "CD2", "NE1", "CE2", "CE3", "CZ2", "CZ3", "CH2"},
    "HIS": {"CG", "ND1", "CD2", "CE1", "NE2"},
    "HID": {"CG", "ND1", "CD2", "CE1", "NE2"},
    "HIE": {"CG", "ND1", "CD2", "CE1", "NE2"},
    "HIP": {"CG", "ND1", "CD2", "CE1", "NE2"},
}
ELEMENT_Z = {"H": 1, "C": 6, "N": 7, "O": 8, "S": 16}

# Expanded sets for specific chemical perceptions
ZINC_BINDER_RES = {'CYS', 'HIS', 'ASP', 'GLU'}
POS_IONIZABLE_RES = {'ARG', 'LYS', 'HIP'}
NEG_IONIZABLE_RES = {'ASP', 'GLU'}

all_atoms = []
pocket1_atoms = []

with open("5RMM_prepared.pqr", "r") as f:
    for line in f:
        if not line.startswith(("ATOM", "HETATM")):
            continue
        try:
            atom_id = int(line[6:11].strip())
            atom_name = line[12:16].strip()
            res_name = line[17:20].strip()
            res_num = int(line[22:26].strip())

            parts = line.split()
            charge = float(parts[-2])
            x, y, z = float(parts[-5]), float(parts[-4]), float(parts[-3])

            symbol = atom_name.lstrip("0123456789")[:1].upper()
            z_num = ELEMENT_Z.get(symbol, 0)

            atom_data = {
                "id": atom_id, "name": atom_name, "res_name": res_name,
                "res_num": res_num, "charge": charge, "z_num": z_num,
                "pos": (x, y, z)
            }
            all_atoms.append(atom_data)

            if res_num in p1_res_nums:
                pocket1_atoms.append(atom_data)

        except (ValueError, IndexError):
            continue

# Create a fast spatial tree of ALL Hydrogens in the protein
hydrogens = [a['pos'] for a in all_atoms if a['z_num'] == 1]
h_tree = cKDTree(hydrogens) if hydrogens else None

pocket1_features = []

# Apply Upgraded Geometric/Physics rules (Matching Step 3 CUDA Kernel)
for atom in pocket1_atoms:
    x, y, z = atom['pos']
    base_feat = {
        "atom_ids": [atom['id']],
        "position": {"x": round(x, 3), "y": round(y, 3), "z": round(z, 3)}
    }

    # 1. H-Bond Acceptor
    if atom['z_num'] in (7, 8) and atom['charge'] <= -0.25:
        feat = base_feat.copy()
        feat.update({"family": "Acceptor", "type": "Geometric_Acceptor"})
        pocket1_features.append(feat)

    # 2. H-Bond Donor (Including Sulfur)
    if atom['z_num'] in (7, 8, 16) and h_tree is not None:
        dist, _ = h_tree.query((x, y, z), k=1, distance_upper_bound=1.2)
        if dist <= 1.2:
            feat = base_feat.copy()
            feat.update({"family": "Donor", "type": "Geometric_Donor"})
            pocket1_features.append(feat)

    # 3. Hydrophobe (Carbon or Sulfur with near-neutral charge)
    # EXCLUDE aromatic atoms to prevent redundant feature overlap!
    is_aromatic = atom['name'] in AROMATIC_RING.get(atom['res_name'], set())

    if atom['z_num'] in (6, 16) and abs(atom['charge']) <= 0.2 and not is_aromatic:
        feat = base_feat.copy()
        feat.update({"family": "Hydrophobe", "type": "Geometric_Hydrophobe"})
        pocket1_features.append(feat)

    # 4. Aromatic
    if is_aromatic:
        feat = base_feat.copy()
        feat.update({"family": "Aromatic", "type": "Geometric_Aromatic"})
        pocket1_features.append(feat)

    # 5. PosIonizable
    if atom['res_name'] in POS_IONIZABLE_RES and atom['z_num'] == 7 and atom['charge'] > 0.0:
        feat = base_feat.copy()
        feat.update({"family": "PosIonizable", "type": "Geometric_PosIonizable"})
        pocket1_features.append(feat)

    # 6. NegIonizable
    if atom['res_name'] in NEG_IONIZABLE_RES and atom['z_num'] == 8 and atom['charge'] < -0.6:
        feat = base_feat.copy()
        feat.update({"family": "NegIonizable", "type": "Geometric_NegIonizable"})
        pocket1_features.append(feat)

    # 7. ZnBinder
    if atom['res_name'] in ZINC_BINDER_RES and (atom['name'] == 'SG' or atom['z_num'] in (7, 8)):
        feat = base_feat.copy()
        feat.update({"family": "ZnBinder", "type": "Geometric_ZnBinder"})
        pocket1_features.append(feat)

elapsed = time.time() - start_time
print(f"  -> Extracted {len(pocket1_features)} features natively (Took {elapsed:.4f} seconds!)")

print("\nStep 3: Saving features to pocket1_pharmacophore_features.json...")
output_json = "pocket1_pharmacophore_features.json"
with open(output_json, "w") as f:
    json.dump(pocket1_features, f, indent=4)

print(f"\nProcess complete! Successfully saved RDKit-free features to '{output_json}'.")

#@title Visualise The Ranked 1 Pocket Electrostatic Surface and Pharmacophore Features
import py3Dmol
import json
import time
import numpy as np
from scipy.spatial import cKDTree

# Map RDKit feature families to the custom py3Dmol colors
feature_colors_py3d = {
    "Donor": "green",
    "Acceptor": "red",
    "Hydrophobe": "yellow",
    "NegIonizable": "magenta",
    "PosIonizable": "cyan",
    "ZnBinder": "blue",
    "Aromatic": "orange",
    "LumpedHydrophobe": "gray"
}

# Load Pocket 1 residues
with open('/content/5RMM_pocket_residues.json', 'r') as f:
    pocket_residues_dict = json.load(f)
pocket1_res_strs = pocket_residues_dict.get("Rank_1", [])
# Extract just the integer residue numbers
p1_res_nums = [int(r[3:]) for r in pocket1_res_strs]

print("\nStep 2: Parsing PQR via text and identifying Native Geometric Pharmacophores...")
start_time = time.time()

AROMATIC_RING = {
    "PHE": {"CG", "CD1", "CD2", "CE1", "CE2", "CZ"},
    "TYR": {"CG", "CD1", "CD2", "CE1", "CE2", "CZ"},
    "TRP": {"CG", "CD1", "CD2", "NE1", "CE2", "CE3", "CZ2", "CZ3", "CH2"},
    "HIS": {"CG", "ND1", "CD2", "CE1", "NE2"},
    "HID": {"CG", "ND1", "CD2", "CE1", "NE2"},
    "HIE": {"CG", "ND1", "CD2", "CE1", "NE2"},
    "HIP": {"CG", "ND1", "CD2", "CE1", "NE2"},
}
ELEMENT_Z = {"H": 1, "C": 6, "N": 7, "O": 8, "S": 16}

# Expanded sets for specific chemical perceptions
ZINC_BINDER_RES = {'CYS', 'HIS', 'ASP', 'GLU'}
POS_IONIZABLE_RES = {'ARG', 'LYS', 'HIP'}
NEG_IONIZABLE_RES = {'ASP', 'GLU'}

all_atoms = []
pocket1_atoms = []

with open("5RMM_prepared.pqr", "r") as f:
    for line in f:
        if not line.startswith(("ATOM", "HETATM")):
            continue
        try:
            atom_id = int(line[6:11].strip())
            atom_name = line[12:16].strip()
            res_name = line[17:20].strip()
            res_num = int(line[22:26].strip())

            parts = line.split()
            charge = float(parts[-2])
            x, y, z = float(parts[-5]), float(parts[-4]), float(parts[-3])

            symbol = atom_name.lstrip("0123456789")[:1].upper()
            z_num = ELEMENT_Z.get(symbol, 0)

            atom_data = {
                "id": atom_id, "name": atom_name, "res_name": res_name,
                "res_num": res_num, "charge": charge, "z_num": z_num,
                "pos": (x, y, z)
            }
            all_atoms.append(atom_data)

            if res_num in p1_res_nums:
                pocket1_atoms.append(atom_data)

        except (ValueError, IndexError):
            continue

# Create a fast spatial tree of ALL Hydrogens in the protein
hydrogens = [a['pos'] for a in all_atoms if a['z_num'] == 1]
h_tree = cKDTree(hydrogens) if hydrogens else None

pocket1_features = []

# Apply Upgraded Geometric/Physics rules
for atom in pocket1_atoms:
    x, y, z = atom['pos']
    base_feat = {
        "atom_ids": [atom['id']],
        "position": {"x": round(x, 3), "y": round(y, 3), "z": round(z, 3)}
    }

    # 1. Determine H-Bond Donor First (N/O/S bound to Hydrogen)
    is_donor = False
    if atom['z_num'] in (7, 8, 16) and h_tree is not None:
        dist, _ = h_tree.query((x, y, z), k=1, distance_upper_bound=1.2)
        if dist <= 1.2:
            is_donor = True
            feat = base_feat.copy()
            feat.update({"family": "Donor", "type": "Geometric_Donor"})
            pocket1_features.append(feat)

    # 2. Determine H-Bond Acceptor
    is_acceptor = False
    if atom['z_num'] == 8 and atom['charge'] <= -0.25:
        # Oxygen with negative charge is generally always an acceptor
        is_acceptor = True
    elif atom['z_num'] == 7 and atom['charge'] <= -0.25:
        # Nitrogen is ONLY an acceptor if it lacks an attached H (not a donor)
        # AND is not a Proline backbone amide (name != 'N')
        # This perfectly isolates unprotonated Histidine nitrogens.
        if not is_donor and atom['name'] != 'N':
            is_acceptor = True

    if is_acceptor:
        feat = base_feat.copy()
        feat.update({"family": "Acceptor", "type": "Geometric_Acceptor"})
        pocket1_features.append(feat)

    # 3. Hydrophobe (Carbon or Sulfur with near-neutral charge)
    if atom['z_num'] in (6, 16) and abs(atom['charge']) <= 0.2:
        feat = base_feat.copy()
        feat.update({"family": "Hydrophobe", "type": "Geometric_Hydrophobe"})
        pocket1_features.append(feat)

    # 4. Aromatic (Pre-defined sidechain ring atoms)
    if atom['name'] in AROMATIC_RING.get(atom['res_name'], set()):
        feat = base_feat.copy()
        feat.update({"family": "Aromatic", "type": "Geometric_Aromatic"})
        pocket1_features.append(feat)

    # 5. PosIonizable
    if atom['res_name'] in POS_IONIZABLE_RES and atom['name'] in {'NZ', 'NH1', 'NH2', 'ND1', 'NE2'}:
        feat = base_feat.copy()
        feat.update({"family": "PosIonizable", "type": "Geometric_PosIonizable"})
        pocket1_features.append(feat)

    # 6. NegIonizable
    if (atom['res_name'] in NEG_IONIZABLE_RES and atom['name'] in {'OD1', 'OD2', 'OE1', 'OE2'}) or atom['name'] == 'OXT':
        feat = base_feat.copy()
        feat.update({"family": "NegIonizable", "type": "Geometric_NegIonizable"})
        pocket1_features.append(feat)

    # 7. ZnBinder
    if atom['res_name'] in ZINC_BINDER_RES and (atom['name'] == 'SG' or atom['z_num'] in (7, 8)):
        feat = base_feat.copy()
        feat.update({"family": "ZnBinder", "type": "Geometric_ZnBinder"})
        pocket1_features.append(feat)

features = pocket1_features

# Initialize py3Dmol
view = py3Dmol.view(width=800, height=600)
pqr_file = "/content/5RMM_prepared.pqr"
with open(pqr_file, 'r') as f:
    view.addModel(f.read(), 'pqr', {'keepH': True})

# Base styles (removed chain constraint to work with PQR)
view.setStyle({}, {'cartoon': {'color': 'white', 'opacity': 0.4}})
pocket_sel = {'resi': p1_res_nums}
view.addStyle(pocket_sel, {'stick': {'colorscheme': 'grayCarbon', 'opacity': 0.8}})
view.addSurface(py3Dmol.VDW, {
    'opacity': 1.0,
    'colorscheme': {'prop': 'partialCharge', 'gradient': 'rwb', 'min': -0.5, 'max': 0.5},
    'wireframe': True
}, pocket_sel)

# Add Residue Labels for Pocket 1
view.addResLabels(pocket_sel, {
    'fontSize': 10,
    'fontColor': 'black',
    'backgroundColor': 'white',
    'showBackground': True,
    'backgroundOpacity': 0.9
})

# Add Atomic Charge Labels for Pocket 1 atoms
view.addPropertyLabels('partialCharge', pocket_sel, {
    'fontSize': 8,
    'fontColor': 'black',
    'showBackground': False,
    'backgroundOpacity': 0.8
})

# Add Pharmacophore Features as Concentric Spheres
features_added = 0
present_families = set()

# Create a Concentric Radius Map to prevent Z-fighting
# Base features are small; Macro electrostatic/aromatic features are larger shells
radius_map = {
    "Donor": 0.35,
    "Acceptor": 0.35,
    "Hydrophobe": 0.40,
    "Aromatic": 0.55,
    "PosIonizable": 0.75,
    "NegIonizable": 0.75,
    "ZnBinder": 0.90
}

for feat in features:
    feat_family = feat.get("family")
    color = feature_colors_py3d.get(feat_family, "white")
    rad = radius_map.get(feat_family, 0.6) # Default radius if not found

    pos = feat.get("position", {})
    if pos:
        present_families.add(feat_family)

        # Draw nested spheres!
        # Base features (<= 0.4) are solid. Macro-features (> 0.4) are wireframe shells.
        view.addSphere({
            'center': {'x': pos.get('x'), 'y': pos.get('y'), 'z': pos.get('z')},
            'radius': rad,
            'color': color,
            'alpha': 0.9 if rad <= 0.4 else 0.7,
            'wireframe': False if rad <= 0.4 else True
        })
        features_added += 1

# Add a 2D Screen Legend for the features present in this pocket
y_pos = 10
for family in sorted(present_families):
    color = feature_colors_py3d.get(family, "white")
    font_color = 'black' if color in ['yellow', 'cyan', 'white'] else 'white'
    view.addLabel(f" {family} ", {
        'position': {'x': 10, 'y': y_pos, 'z': 0},
        'useScreen': True,
        'alignment': 'topLeft',
        'backgroundColor': color,
        'fontColor': font_color,
        'backgroundOpacity': 0.8,
        'fontSize': 14
    })
    y_pos += 25

print(f"Mapped {features_added} pharmacophore features for Pocket 1 residues.")

view.setBackgroundColor('white')
view.zoomTo(pocket_sel)
view.show()

"""# 🔬 Model Evaluation: P2Rank Inspiration & Real-World Translation

This notebook is a highly ambitious proof-of-concept that successfully translates the theoretical framework of classical pocket-prediction algorithms into a modern, highly parallelized GPU hardware environment.

## 1. Inspiration from P2Rank & The Shift to XGBoost-GPU
The architectural flow of this pipeline is a direct, GPU-accelerated homage to **P2Rank**, a widely used template-free machine learning method for ligand binding site prediction. This notebook mimics P2Rank’s core logic:
* **Solvent-Accessible Surface (SAS) Representation:** Generating a cloud of points representing the solvent-accessible surface around the protein.
* **Localized Neighborhood Featurization:** Calculating properties for each surface point based on surrounding atoms within a specific spatial cutoff.
* **Spatial Clustering:** Using DBSCAN (instead of P2Rank's custom hierarchical clustering) to group high-probability points into discrete pockets.

**Why XGBoost-GPU instead of Random Forest?**
P2Rank utilizes a traditional Random Forest classifier running on the CPU. We replaced this with a GPU-native **XGBoost regressor** (using `tree_method='hist'`). This allows for **zero-copy data transfers**; our CuPy feature arrays stay entirely in VRAM, completely avoiding the PCI-e bottleneck. XGBoost's GPU histogram algorithm can process millions of data points exponentially faster than CPU-bound Random Forests, making it feasible to analyze massive protein complexes in seconds.

## 2. Why it Would Fail in Real-World Scenarios (Currently)
While the C++ spatial hashing and parallelization are computationally brilliant, the model is currently a biophysical simulation:
* **Mock Chemical Features & Targets (Garbage In, Garbage Out):** The model currently learns the relationship between partially simulated features (like random hydrophobicity and amine distributions) and a randomly generated target array (`Y_train_gpu`).
* **Static "Lock-and-Key" Fallacy:** Evaluating a single, rigid PDB snapshot ignores protein dynamics. Pockets often only form via induced fit upon ligand binding.
* **Blindness to Solvent and Co-factors:** Ignoring crystallographic waters and metal ions drastically alters the true localized electrostatic potential.

## 3. Improving the Model with Real X-ray Fragment Structures
To fix the "Garbage In, Garbage Out" problem, we can leverage the massive wealth of real-world data available for this target. For proteins like SARS-CoV-2 Mac1 (5RMM), hundreds of **X-ray fragment-bound crystal structures** exist.
* **Data Overlay:** We can superimpose all these known fragment-bound structures onto our reference apo structure.
* **Ground Truth Labeling:** For our generated SAS points, any point falling within a defined radius (e.g., 2.0 Å) of a bound fragment atom is labeled as `1` (True Pocket). All other points are labeled `0`.
* **Training on Reality:** By training the XGBoost model on this labeled dataset, the model will learn the *actual* electrostatic, hydrophobic, and steric patterns that dictate true protein-ligand interactions, effectively transforming it from a simulation into a predictive drug-discovery tool.

## 4. Requirements for a Production-Ready Pipeline
To evolve this into a robust cheminformatics tool, the pipeline needs:
* **True Cheminformatics Integration:** Replacing all `cp.random` features with robust invariant extraction (e.g., RDKit SMARTS mapping for amine nitrogens and precise biophysical partial charges).
* **Supervised Knowledge Distillation:** Training on massive, curated datasets (like scPDB, PDBbind, or fragment screens) to establish real ground-truth weights.
* **Accounting for Flexibility:** Ingesting structural ensembles or Molecular Dynamics (MD) frames rather than a single rigid crystal structure to find transient or cryptic pockets.
* **Robust Kernel Memory Management:** Dynamic memory batching for the CUDA spatial hashing to ensure massive multimeric complexes do not exceed GPU VRAM limits.

## XGBoost-GPU vs. Random Forest and the Future of E3 Equivariant Neural Networks

### What is the XGBoost-GPU Model?
XGBoost (eXtreme Gradient Boosting) is a highly optimized, distributed gradient boosting library designed to be efficient, flexible, and portable. The GPU-accelerated version (XGBoost-GPU) leverages NVIDIA GPUs to parallelize the construction of decision trees. This allows it to process massive datasets—such as our millions of simulated protein surface points—exponentially faster than traditional CPU-based models.

### How does it work?
XGBoost uses an ensemble machine learning technique called **gradient boosting**. Instead of building one massive model, it builds a sequence of shallow, "weak" decision trees. Each new tree is specifically trained to correct the residual errors (the mistakes) made by the combined ensemble of all previous trees.
By setting `tree_method='hist'`, the algorithm groups continuous continuous features (like electrostatic values) into discrete histogram bins. This allows the thousands of CUDA cores on the GPU to find the optimal mathematical split points for the decision trees almost instantaneously.

### XGBoost vs. Random Forest (The P2Rank Baseline)
* **Ensemble Strategy:** Random Forest (the algorithm powering P2Rank) builds many independent decision trees in parallel and averages their predictions. XGBoost builds trees sequentially, with each tree actively learning from the mistakes of its predecessors.
* **Hardware Efficiency:** While Random Forests are typically CPU-bound and scale linearly, XGBoost's histogram-based algorithm was built natively for GPU acceleration, offering massive speedups and zero-copy VRAM execution.
* **Accuracy:** Because gradient boosting aggressively minimizes a specific loss function step-by-step, XGBoost frequently yields higher accuracy for complex tabular data compared to Random Forests.

### The Next Evolution: E(3) Equivariant Graph Neural Networks
While XGBoost-GPU is blisteringly fast, it relies entirely on **hand-engineered features**. We had to manually calculate metrics like "hydrophobic neighbor counts within 4.0 Å." This process strips away the actual 3D geometry of the binding pocket.

To drastically improve binding site predictions, an **E(3) Equivariant Neural Network** could replace XGBoost:
* **Native 3D Understanding:** "E(3) Equivariance" means the network natively respects 3D Euclidean space (translations, rotations, and reflections). If you rotate the protein 90 degrees, the network's internal mathematical representations rotate perfectly in sync. It doesn't need to "re-learn" the protein from a new angle.
* **No Feature Engineering:** Instead of manual distance cutoffs, an E(3) network ingests the raw 3D atomic coordinates and their chemical identities directly as a spatial graph.
* **Directional Biophysics:** Traditional models only know scalar distances (e.g., "an oxygen is 3Å away"). E(3) networks utilize tensor mathematics to learn **directional vectors**. It can learn that a specific hydrogen bond donor is pointing at the exact required angle to interact with a ligand, vastly improving the detection of highly specific, cryptic binding sites.

## Scaling to the Proteome: From XGBoost to E(3) Equivariant Networks

The ultimate vision for this pipeline is not just to analyze a single protein, but to orchestrate a massive, proteome-wide data generation engine that feeds into next-generation generative AI. Here is how we can scale this approach:

### 1. High-Throughput Pocket Prediction (XGBoost-GPU)
Because our XGBoost model processes spatial hashing and mathematics natively on the GPU, it is blisteringly fast. We can deploy this pipeline across millions of predicted protein structures (such as the entire AlphaFold database).
*   **The Output:** A massive database containing millions of identified binding pockets, complete with their high-resolution biophysical and geometric surface descriptions.

### 2. Generating the "Ground Truth" Pharmacophore Dataset
For every pocket identified in Step 1, we programmatically extract the complementary chemical features required to bind to it (just as we did for Pocket 1).
*   **The Output:** We map the pocket's hydrogen bond donors, acceptors, and hydrophobic patches to create an *idealized 3D ligand pharmacophore model*. This results in a massive paired dataset: `[3D Pocket Geometry] -> [Ideal 3D Ligand Pharmacophore]`.

### 3. Training an E(3) Equivariant Neural Network
With millions of paired examples, we can now train an E(3) Equivariant Graph Neural Network.
*   **Native 3D Learning:** E(3) networks inherently understand 3D space, rotation, and translation. We feed the raw 3D atomic coordinates of the pockets into the network as input, and provide the idealized 3D pharmacophore as the target output.
*   **Learning the Rules of Binding:** The E(3) network learns the universal, directional biophysics of protein-ligand interactions without relying on human-engineered features.

### 4. Zero-Shot De Novo Drug Design
Once trained, this E(3) network becomes a powerful generative engine. When presented with a completely novel protein target or a newly mutated binding site, the network can instantly predict the perfect 3D pharmacophore model required to drug it. This precise 3D blueprint can then be used to rapidly screen billion-compound virtual libraries or guide diffusion models to generate entirely new, highly specific therapeutic molecules from scratch.
"""

import os
from google.colab import files

# NOTE: Google Colab does not natively expose the live .ipynb file to the runtime.
# Step 1: Download the notebook manually via File -> Download -> Download .ipynb
# Step 2: Upload that downloaded .ipynb file to the Colab files pane (left sidebar).
# Step 3: Update the 'notebook_path' variable below to match your filename.

notebook_path = '/content/XGBoost_GPU (2).ipynb' # Replace with your actual uploaded filename

if os.path.exists(notebook_path):
    # Convert the notebook to HTML, including outputs
    !jupyter nbconvert --to html "{notebook_path}"

    # Trigger the download of the resulting HTML file
    html_file = notebook_path.replace('.ipynb', '.html')
    if os.path.exists(html_file):
        print(f"Successfully converted. Downloading {html_file}...")
        files.download(html_file)
    else:
        print("Conversion failed.")
else:
    print(f"File '{notebook_path}' not found.\nPlease upload your .ipynb file to the runtime first.")